// Mock data for development
export const mockAudits = [
  {
    id: "1",
    name: "DeFi Protocol V2",
    repo: "defi-protocol/contracts",
    commit: "a1b2c3d",
    chains: ["Ethereum", "Arbitrum"],
    status: "in-progress",
    scopeSize: 12,
    riskScore: 78,
    findings: {
      critical: 2,
      high: 5,
      medium: 8,
      low: 12,
      info: 5,
    },
    lastActivity: "2 hours ago",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "NFT Marketplace",
    repo: "nft-market/core",
    commit: "e4f5g6h",
    chains: ["Base", "Optimism"],
    status: "in-progress",
    scopeSize: 8,
    riskScore: 45,
    findings: {
      critical: 0,
      high: 2,
      medium: 4,
      low: 8,
      info: 3,
    },
    lastActivity: "5 hours ago",
    createdAt: "2024-01-20",
  },
  {
    id: "3",
    name: "Lending Platform",
    repo: "lending-proto/contracts",
    commit: "i7j8k9l",
    chains: ["Ethereum"],
    status: "completed",
    scopeSize: 15,
    riskScore: 92,
    findings: {
      critical: 3,
      high: 7,
      medium: 10,
      low: 15,
      info: 8,
    },
    lastActivity: "1 day ago",
    createdAt: "2024-01-10",
  },
  {
    id: "4",
    name: "Cross-Chain Bridge",
    repo: "bridge-protocol/core",
    commit: "m1n2o3p",
    chains: ["Ethereum", "Polygon", "Avalanche"],
    status: "in-progress",
    scopeSize: 18,
    riskScore: 85,
    findings: {
      critical: 1,
      high: 6,
      medium: 12,
      low: 18,
      info: 7,
    },
    lastActivity: "30 minutes ago",
    createdAt: "2024-01-22",
  },
  {
    id: "5",
    name: "Staking Rewards System",
    repo: "staking-rewards/contracts",
    commit: "q4r5s6t",
    chains: ["Ethereum"],
    status: "completed",
    scopeSize: 6,
    riskScore: 32,
    findings: {
      critical: 0,
      high: 1,
      medium: 3,
      low: 5,
      info: 4,
    },
    lastActivity: "3 days ago",
    createdAt: "2024-01-05",
  },
  {
    id: "6",
    name: "DAO Governance",
    repo: "dao-governance/core",
    commit: "u7v8w9x",
    chains: ["Ethereum", "Base"],
    status: "pending",
    scopeSize: 10,
    riskScore: 0,
    findings: {
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      info: 0,
    },
    lastActivity: "1 week ago",
    createdAt: "2024-01-25",
  },
  {
    id: "7",
    name: "Token Vesting Contract",
    repo: "vesting/contracts",
    commit: "y1z2a3b",
    chains: ["Arbitrum"],
    status: "completed",
    scopeSize: 4,
    riskScore: 28,
    findings: {
      critical: 0,
      high: 0,
      medium: 2,
      low: 4,
      info: 2,
    },
    lastActivity: "5 days ago",
    createdAt: "2024-01-08",
  },
  {
    id: "8",
    name: "Perpetual Futures DEX",
    repo: "perp-dex/contracts",
    commit: "c4d5e6f",
    chains: ["Ethereum", "Optimism"],
    status: "in-progress",
    scopeSize: 22,
    riskScore: 94,
    findings: {
      critical: 4,
      high: 9,
      medium: 15,
      low: 20,
      info: 10,
    },
    lastActivity: "1 hour ago",
    createdAt: "2024-01-12",
  },
  {
    id: "9",
    name: "Yield Aggregator",
    repo: "yield-aggregator/core",
    commit: "g7h8i9j",
    chains: ["Polygon", "Avalanche"],
    status: "completed",
    scopeSize: 14,
    riskScore: 56,
    findings: {
      critical: 0,
      high: 3,
      medium: 7,
      low: 11,
      info: 6,
    },
    lastActivity: "2 weeks ago",
    createdAt: "2024-01-03",
  },
  {
    id: "10",
    name: "Options Protocol",
    repo: "options-proto/contracts",
    commit: "k1l2m3n",
    chains: ["Ethereum"],
    status: "pending",
    scopeSize: 16,
    riskScore: 0,
    findings: {
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      info: 0,
    },
    lastActivity: "3 days ago",
    createdAt: "2024-01-24",
  },
]

export const mockAuditDetails = {
  id: "1",
  name: "DeFi Protocol V2",
  description:
    "Comprehensive security audit of DeFi Protocol V2 including core lending, borrowing, and liquidation mechanisms.",
  repo: "defi-protocol/contracts",
  commit: "a1b2c3d4e5f6g7h8i9j0",
  chains: ["Ethereum", "Arbitrum"],
  status: "in-progress",
  tags: ["DeFi", "Lending", "High-Value"],
  scope: {
    contracts: 12,
    linesOfCode: 3450,
    verified: 10,
    proxies: 3,
  },
  findings: {
    critical: 2,
    high: 5,
    medium: 8,
    low: 12,
    info: 5,
  },
  timeline: [
    {
      id: "1",
      action: "Audit created",
      user: "0x1234...5678",
      timestamp: "2024-01-15T10:00:00Z",
    },
    {
      id: "2",
      action: "Scope defined",
      user: "0x1234...5678",
      timestamp: "2024-01-15T11:30:00Z",
    },
    {
      id: "3",
      action: "Critical finding added",
      user: "0x8765...4321",
      timestamp: "2024-01-16T14:20:00Z",
      details: "Reentrancy in withdraw function",
    },
  ],
}

export const mockFindings = [
  {
    id: "1",
    title: "Reentrancy vulnerability in withdraw function",
    severity: "CRITICAL" as const,
    status: "accepted",
    contract: "LendingPool.sol",
    category: "Reentrancy",
    cwe: "CWE-107",
    reporter: "0x1234...5678",
    createdAt: "2024-01-16",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "2",
    title: "Missing access control on admin functions",
    severity: "HIGH" as const,
    status: "in_review",
    contract: "Governance.sol",
    category: "Access Control",
    cwe: "CWE-284",
    reporter: "0x8765...4321",
    createdAt: "2024-01-17",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "3",
    title: "Integer overflow in reward calculation",
    severity: "HIGH" as const,
    status: "accepted",
    contract: "RewardDistributor.sol",
    category: "Math",
    cwe: "CWE-190",
    reporter: "0x1234...5678",
    createdAt: "2024-01-18",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "4",
    title: "Unchecked return value from external call",
    severity: "MEDIUM" as const,
    status: "draft",
    contract: "TokenSwap.sol",
    category: "Error Handling",
    cwe: "CWE-252",
    reporter: "0x8765...4321",
    createdAt: "2024-01-19",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "5",
    title: "Gas optimization: Loop can be optimized",
    severity: "LOW" as const,
    status: "accepted",
    contract: "BatchProcessor.sol",
    category: "Gas Optimization",
    cwe: "N/A",
    reporter: "0x1234...5678",
    createdAt: "2024-01-20",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "6",
    title: "Front-running vulnerability in token swap",
    severity: "CRITICAL" as const,
    status: "in_review",
    contract: "SwapRouter.sol",
    category: "MEV",
    cwe: "CWE-362",
    reporter: "0x2345...6789",
    createdAt: "2024-01-21",
    auditId: "8",
    auditName: "Perpetual Futures DEX",
  },
  {
    id: "7",
    title: "Centralization risk in bridge validator set",
    severity: "HIGH" as const,
    status: "disputed",
    contract: "BridgeValidator.sol",
    category: "Centralization",
    cwe: "N/A",
    reporter: "0x3456...7890",
    createdAt: "2024-01-22",
    auditId: "4",
    auditName: "Cross-Chain Bridge",
  },
  {
    id: "8",
    title: "Timestamp manipulation in reward distribution",
    severity: "MEDIUM" as const,
    status: "accepted",
    contract: "RewardManager.sol",
    category: "Time Manipulation",
    cwe: "CWE-829",
    reporter: "0x1234...5678",
    createdAt: "2024-01-23",
    auditId: "5",
    auditName: "Staking Rewards System",
  },
  {
    id: "9",
    title: "Denial of service via unbounded loop",
    severity: "HIGH" as const,
    status: "accepted",
    contract: "VaultManager.sol",
    category: "DoS",
    cwe: "CWE-834",
    reporter: "0x4567...8901",
    createdAt: "2024-01-19",
    auditId: "9",
    auditName: "Yield Aggregator",
  },
  {
    id: "10",
    title: "Insufficient input validation on deposit amount",
    severity: "MEDIUM" as const,
    status: "in_review",
    contract: "Vault.sol",
    category: "Input Validation",
    cwe: "CWE-20",
    reporter: "0x5678...9012",
    createdAt: "2024-01-20",
    auditId: "9",
    auditName: "Yield Aggregator",
  },
  {
    id: "11",
    title: "Oracle price manipulation vulnerability",
    severity: "CRITICAL" as const,
    status: "accepted",
    contract: "PriceOracle.sol",
    category: "Oracle Manipulation",
    cwe: "N/A",
    reporter: "0x6789...0123",
    createdAt: "2024-01-14",
    auditId: "8",
    auditName: "Perpetual Futures DEX",
  },
  {
    id: "12",
    title: "Flash loan attack vector in liquidation",
    severity: "CRITICAL" as const,
    status: "accepted",
    contract: "Liquidator.sol",
    category: "Flash Loan",
    cwe: "N/A",
    reporter: "0x1234...5678",
    createdAt: "2024-01-15",
    auditId: "3",
    auditName: "Lending Platform",
  },
  {
    id: "13",
    title: "Missing event emission for critical state changes",
    severity: "LOW" as const,
    status: "accepted",
    contract: "Governor.sol",
    category: "Best Practices",
    cwe: "N/A",
    reporter: "0x7890...1234",
    createdAt: "2024-01-21",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "14",
    title: "Unsafe type casting in price calculation",
    severity: "HIGH" as const,
    status: "in_review",
    contract: "PriceFeed.sol",
    category: "Type Safety",
    cwe: "CWE-704",
    reporter: "0x8901...2345",
    createdAt: "2024-01-16",
    auditId: "8",
    auditName: "Perpetual Futures DEX",
  },
  {
    id: "15",
    title: "Incorrect slippage protection implementation",
    severity: "MEDIUM" as const,
    status: "accepted",
    contract: "Router.sol",
    category: "Logic Error",
    cwe: "N/A",
    reporter: "0x9012...3456",
    createdAt: "2024-01-22",
    auditId: "2",
    auditName: "NFT Marketplace",
  },
  {
    id: "16",
    title: "Weak randomness in NFT trait generation",
    severity: "MEDIUM" as const,
    status: "disputed",
    contract: "NFTMinter.sol",
    category: "Randomness",
    cwe: "CWE-338",
    reporter: "0x0123...4567",
    createdAt: "2024-01-23",
    auditId: "2",
    auditName: "NFT Marketplace",
  },
  {
    id: "17",
    title: "Signature replay attack possible",
    severity: "HIGH" as const,
    status: "accepted",
    contract: "MetaTransaction.sol",
    category: "Signature Verification",
    cwe: "CWE-294",
    reporter: "0x1234...5678",
    createdAt: "2024-01-17",
    auditId: "4",
    auditName: "Cross-Chain Bridge",
  },
  {
    id: "18",
    title: "Improper access control on emergency functions",
    severity: "CRITICAL" as const,
    status: "accepted",
    contract: "EmergencyModule.sol",
    category: "Access Control",
    cwe: "CWE-284",
    reporter: "0x2345...6789",
    createdAt: "2024-01-13",
    auditId: "3",
    auditName: "Lending Platform",
  },
  {
    id: "19",
    title: "Inconsistent state after failed external call",
    severity: "HIGH" as const,
    status: "in_review",
    contract: "BridgeCore.sol",
    category: "State Management",
    cwe: "CWE-754",
    reporter: "0x3456...7890",
    createdAt: "2024-01-23",
    auditId: "4",
    auditName: "Cross-Chain Bridge",
  },
  {
    id: "20",
    title: "Outdated compiler version with known bugs",
    severity: "INFO" as const,
    status: "accepted",
    contract: "All contracts",
    category: "Compiler",
    cwe: "N/A",
    reporter: "0x4567...8901",
    createdAt: "2024-01-21",
    auditId: "1",
    auditName: "DeFi Protocol V2",
  },
  {
    id: "21",
    title: "Missing natspec documentation",
    severity: "INFO" as const,
    status: "accepted",
    contract: "Multiple contracts",
    category: "Documentation",
    cwe: "N/A",
    reporter: "0x5678...9012",
    createdAt: "2024-01-18",
    auditId: "5",
    auditName: "Staking Rewards System",
  },
  {
    id: "22",
    title: "Inefficient storage layout",
    severity: "LOW" as const,
    status: "in_review",
    contract: "Storage.sol",
    category: "Gas Optimization",
    cwe: "N/A",
    reporter: "0x6789...0123",
    createdAt: "2024-01-15",
    auditId: "8",
    auditName: "Perpetual Futures DEX",
  },
  {
    id: "23",
    title: "Potential precision loss in division",
    severity: "MEDIUM" as const,
    status: "accepted",
    contract: "Calculator.sol",
    category: "Math",
    cwe: "CWE-1339",
    reporter: "0x7890...1234",
    createdAt: "2024-01-10",
    auditId: "9",
    auditName: "Yield Aggregator",
  },
  {
    id: "24",
    title: "Lack of pause mechanism for emergencies",
    severity: "MEDIUM" as const,
    status: "disputed",
    contract: "Core.sol",
    category: "Best Practices",
    cwe: "N/A",
    reporter: "0x8901...2345",
    createdAt: "2024-01-24",
    auditId: "4",
    auditName: "Cross-Chain Bridge",
  },
  {
    id: "25",
    title: "Hardcoded gas limits may cause failures",
    severity: "LOW" as const,
    status: "accepted",
    contract: "Executor.sol",
    category: "Gas",
    cwe: "N/A",
    reporter: "0x9012...3456",
    createdAt: "2024-01-19",
    auditId: "8",
    auditName: "Perpetual Futures DEX",
  },
]

export const mockFindingDetail = {
  id: "1",
  title: "Reentrancy vulnerability in withdraw function",
  severity: "CRITICAL" as const,
  status: "accepted",
  contract: "LendingPool.sol",
  category: "Reentrancy",
  cwe: "CWE-107",
  owasp: "A1:2021 - Broken Access Control",
  reporter: "0x1234...5678",
  createdAt: "2024-01-16T10:00:00Z",
  updatedAt: "2024-01-18T15:30:00Z",
  auditId: "1",
  auditName: "DeFi Protocol V2",
  description: `The \`withdraw\` function in LendingPool.sol makes an external call to transfer ETH before updating the user's balance. This creates a classic reentrancy vulnerability where a malicious contract can recursively call withdraw before the balance is updated.`,
  impact: `An attacker can drain all ETH from the lending pool by repeatedly calling the withdraw function before their balance is updated. This could result in complete loss of user funds.`,
  likelihood: "High - The vulnerability is easily exploitable with a simple malicious contract.",
  exploitScenario: `1. Attacker deploys a malicious contract with a fallback function
2. Attacker deposits 1 ETH into the lending pool
3. Attacker calls withdraw, which triggers the fallback function
4. Fallback function calls withdraw again before balance is updated
5. Process repeats until pool is drained`,
  affectedLines: "LendingPool.sol:145-152",
  reproduction: `\`\`\`solidity
contract Exploit {
    LendingPool pool;
    
    constructor(address _pool) {
        pool = LendingPool(_pool);
    }
    
    function attack() external payable {
        pool.deposit{value: 1 ether}();
        pool.withdraw(1 ether);
    }
    
    receive() external payable {
        if (address(pool).balance >= 1 ether) {
            pool.withdraw(1 ether);
        }
    }
}
\`\`\``,
  recommendation: `Follow the checks-effects-interactions pattern:

\`\`\`solidity
function withdraw(uint256 amount) external {
    require(balances[msg.sender] >= amount, "Insufficient balance");
    
    // Update state BEFORE external call
    balances[msg.sender] -= amount;
    
    // External call last
    (bool success, ) = msg.sender.call{value: amount}("");
    require(success, "Transfer failed");
}
\`\`\`

Alternatively, use OpenZeppelin's ReentrancyGuard modifier.`,
  comments: [
    {
      id: "1",
      author: "0x8765...4321",
      content: "Confirmed. I was able to reproduce this with the provided PoC.",
      timestamp: "2024-01-17T09:00:00Z",
    },
    {
      id: "2",
      author: "0x1234...5678",
      content: "Client has acknowledged and is working on a fix.",
      timestamp: "2024-01-18T15:30:00Z",
    },
  ],
}
